title: Documentação do Compilador COMP1
description: Documentação para um compilador estilo Python construído com Flex e Bison
theme: jekyll-theme-cayman
baseurl: /COMP1-Equipe-1
url: https://felipecampelo.github.io
show_downloads: true
github:
  repository_url: https://github.com/felipecampelo/COMP1-Equipe-1
